import { NextRequest, NextResponse } from 'next/server';
import { generateJSON } from '@/lib/ai';

export const maxDuration = 60;

/**
 * POST /api/conjugate
 * Body: { verb, english, verbCase, past[8], present[8]|null, future[8]|null, imperative[3]|null }
 * Returns pronunciation (transliteration) for every form of a table built by
 * lib/conjugate.ts, plus a short list of anything that looks wrong in the
 * Arabic for Palestinian (Jerusalem / Bethlehem) speech.
 */

const SYSTEM = `You are a Palestinian Arabic teacher (Jerusalem / Bethlehem dialect) who teaches with Basil Zboun's "Arabic Made Easy" method.
You get a verb conjugation table that was generated by rules. For EVERY form, give its pronunciation in simple Latin letters, exactly as a Jerusalem/Bethlehem speaker says it:
- ḥ = ح, kh = خ, gh = غ, ʕ = ع, ʔ = glottal stop (also how ق is said in the city), ṣ ḍ ṭ ẓ = emphatic letters, long vowels ā ī ū ē ō, sh = ش
- Present: ba- for أنا (bakt(i)b), bti-/bit- for إنتا/إنتي/هيّا/إنتو, bi- for هوّ/همّا, mni- for إحنا. Future: raḥ + form without b-.
- Past هيّا and أنا are written the same in Arabic but sound different (katbat vs katabt) — reflect the real sound.
Keep the arrays the same length and order as the input. Use "" for a missing form.
Then, in "issues", list ONLY real mistakes in the Arabic forms for Palestinian speech (wrong vowel pattern, wrong form) as short English sentences that name the form and the correct one. Return an empty list if the table is right. Do not comment on spelling of tashkeel.`;

const ARR = { type: 'array', items: { type: 'string' } };
const SCHEMA = {
  type: 'object',
  properties: {
    past: ARR,
    present: ARR,
    future: ARR,
    imperative: ARR,
    issues: ARR,
  },
  required: ['past', 'present', 'future', 'imperative', 'issues'],
};

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    if (!body?.verb || !Array.isArray(body.past)) {
      return NextResponse.json({ error: 'verb and past[] required' }, { status: 400 });
    }
    const persons = ['أنا', 'إنتا', 'إنتي', 'هوّ', 'هيّا', 'إحنا', 'إنتو', 'همّا'];
    const rows = (name: string, arr: string[] | null) =>
      arr ? `${name}:\n${arr.map((f, i) => `  ${i + 1}. ${persons[i] ?? ['to a man', 'to a woman', 'to a group'][i]}: ${f}`).join('\n')}` : `${name}: (none)`;
    const prompt = [
      `Verb: ${body.verb} — "${body.english}" (case: ${body.verbCase})`,
      rows('past', body.past),
      rows('present', body.present),
      rows('future', body.future),
      body.imperative
        ? `imperative:\n${body.imperative.map((f: string, i: number) => `  ${i + 1}. ${['to a man', 'to a woman', 'to a group'][i]}: ${f}`).join('\n')}`
        : 'imperative: (none)',
    ].join('\n\n');

    const { data } = await generateJSON<{
      past: string[];
      present: string[];
      future: string[];
      imperative: string[];
      issues: string[];
    }>({
      system: SYSTEM,
      messages: [{ role: 'user', content: prompt }],
      schema: SCHEMA,
      tier: 'smart',
      maxTokens: 1500,
    });
    if (!data) return NextResponse.json({ error: 'No answer from the AI' }, { status: 502 });
    return NextResponse.json(data);
  } catch (err: any) {
    console.error('conjugate error:', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
